// Shim de tipos para date-fns v3 en proyectos CommonJS con moduleResolution: node.
// date-fns v3 solo publica index.d.mts (ESM), no index.d.ts (CJS).
// Con moduleResolution: node, TypeScript no puede resolver el export map del package.json
// y necesita este shim para encontrar los tipos.
declare module 'date-fns' {
  export {
    addDays,
    addWeeks,
    addMonths,
    addYears,
    addHours,
    addMinutes,
    addSeconds,
    subDays,
    subWeeks,
    subMonths,
    subYears,
    startOfDay,
    endOfDay,
    startOfWeek,
    endOfWeek,
    startOfMonth,
    endOfMonth,
    startOfYear,
    endOfYear,
    format,
    formatDistance,
    formatDistanceToNow,
    formatRelative,
    parseISO,
    parse,
    isValid,
    isAfter,
    isBefore,
    isEqual,
    isSameDay,
    isSameMonth,
    isSameYear,
    differenceInDays,
    differenceInWeeks,
    differenceInMonths,
    differenceInYears,
    differenceInHours,
    differenceInMinutes,
    differenceInSeconds,
    differenceInCalendarDays,
    eachDayOfInterval,
    eachWeekOfInterval,
    eachMonthOfInterval,
    getDay,
    getDate,
    getMonth,
    getYear,
    getHours,
    getMinutes,
    getSeconds,
    setDay,
    setDate,
    setMonth,
    setYear,
    setHours,
    setMinutes,
    setSeconds,
    max,
    min,
    compareAsc,
    compareDesc,
    isWeekend,
    getWeek,
    getISOWeek,
    toDate,
  } from 'date-fns/index.d.mts';
}
